---
- name: Install wordpress on CentOS 7
  gather_facts: no
  hosts: all
  tasks:
    - name: Install httpd
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - php
        - mariadb-server
        - mysql
        - elinks
        - php-mysql
        - php-gd

      ignore_errors: yes


    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/



    - name: Unzip wordpress
      unarchive:
        src: /tmp/wordpress-5.0.1.tar.gz
        dest: /var/www/html
        remote_src: yes



    - name: Move file
      shell: "mv /var/www/html/wordpress/*  /var/www/html/"
      ignore_errors: yes


    - name: run apache
      systemd:
        name: httpd
        state: started
        enabled: yes
      ignore_errors: yes
